"""
app/cache.py
------------
Helpers for reading pre-computed JSON cache files.

The cache lives in  $DATA_DIR/cache/  and is generated by
kg_data/generate_cache.py after every rebuild.  When a cache file is present
the routes return it instantly (no KG query needed).  When it is absent the
routes fall back to a live KG query.
"""

import os
import json
from typing import Any

_DATA_DIR = os.environ.get("DATA_DIR", "/data")
_CACHE_DIR = os.path.join(_DATA_DIR, "cache")


def cache_path(name: str) -> str:
    """Absolute path for a named cache file, e.g. 'samples.json'."""
    return os.path.join(_CACHE_DIR, name)


def read_cache(name: str) -> Any | None:
    """
    Return the parsed JSON from the cache file, or None if it doesn't exist.
    Failures (corrupt JSON, permission errors) are swallowed so the route
    can fall back gracefully to a live query.
    """
    path = cache_path(name)
    try:
        with open(path) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return None
