"""
/api/properties — lists CalculatedProperty instances from the knowledge graph.

Dynamically discovers all ASMO-typed property instances that are linked to a
workflow via asmo:wasCalculatedBy (i.e. actual *calculated* properties).
Input parameters (linked via asmo:hasInputParameter) are excluded.

Each record contains:
  id, type, label, value (scalar float or null for arrays), value_is_array,
  unit, unit_uri, workflow_id, sample_ids (list of sample URIs linked via
  asmo:wasCalculatedBy → sample prov:wasGeneratedBy)

The route serves the pre-computed cache file (generated by
kg_data/generate_cache.py) when available, falling back to a live query.

Two endpoints, because the UI needs two very different things:

  GET /api/properties/summary
      One row per property type with counts, unit and min/max/mean. This is what
      the Properties tab renders -- 21 rows, a couple of kB.

  GET /api/properties?type=&search=&limit=&offset=
      Individual records, paginated, for one expanded card. Returns
      {items, total, limit, offset}.

Previously the tab downloaded every instance -- 109,821 records, 47 MB, 6.2 s --
purely to compute per-type aggregates and then show 21 cards. The full list is
still loaded server-side (once, memoised) but never crosses the wire whole.
"""

from fastapi import APIRouter
from app.graph_state import get_kg
from app.cache import read_cache

router = APIRouter(prefix="/api/properties", tags=["properties"])

_ASMO_NS = "http://purls.helmholtz-metadaten.de/asmo/"
_PROV_NS = "http://www.w3.org/ns/prov#"
_CMSO_NS = "http://purls.helmholtz-metadaten.de/cmso/"

# Types that are NOT properties (workflows, potentials, methods, etc.)
_SKIP_TYPES = {
    f"{_ASMO_NS}EnergyCalculation",
    f"{_ASMO_NS}Simulation",
    f"{_ASMO_NS}InteratomicPotential",
    f"{_ASMO_NS}ModifiedEmbeddedAtomModel",
    f"{_ASMO_NS}EmbeddedAtomModel",
    f"{_ASMO_NS}PairPotential",
    f"{_ASMO_NS}MolecularStatics",
    f"{_ASMO_NS}MolecularDynamics",
    f"{_ASMO_NS}DensityFunctionalTheory",
}


def _build_properties_live():
    """Live query — discovers all calculated properties dynamically."""
    from rdflib import URIRef, RDF, RDFS

    kg = get_kg()
    g = kg.graph

    _CMSO_SAMPLE = URIRef(f"{_CMSO_NS}AtomicScaleSample")
    _PROV_GEN_BY = URIRef(f"{_PROV_NS}wasGeneratedBy")
    _HAS_VALUE = URIRef(f"{_ASMO_NS}hasValue")
    _HAS_UNIT = URIRef(f"{_ASMO_NS}hasUnit")
    _CALC_BY = URIRef(f"{_ASMO_NS}wasCalculatedBy")
    _HAS_PATH = URIRef(f"{_CMSO_NS}hasPath")

    def _exists(node):
        return node is not None and any(
            True for _ in g.triples((URIRef(str(node)), RDF.type, _CMSO_SAMPLE))
        )

    # workflow → samples map
    sim_to_samples: dict[str, list[str]] = {}
    for s, _, wf in g.triples((None, _PROV_GEN_BY, None)):
        if _exists(s):
            sim_to_samples.setdefault(str(wf), []).append(str(s))

    records = []

    # Find all property nodes that have asmo:wasCalculatedBy (= calculated properties)
    for prop_node, _, wf_node in g.triples((None, _CALC_BY, None)):
        # Determine the property type from rdf:type
        prop_type_uri = g.value(prop_node, RDF.type)
        if prop_type_uri is None:
            continue
        type_str = str(prop_type_uri)
        if type_str in _SKIP_TYPES or not type_str.startswith(_ASMO_NS):
            continue

        pt = type_str[len(_ASMO_NS) :]

        label_lit = g.value(prop_node, RDFS.label)
        label = str(label_lit) if label_lit else pt

        value_lit = g.value(prop_node, _HAS_VALUE)
        has_path = g.value(prop_node, _HAS_PATH) is not None

        if value_lit is not None:
            try:
                import math

                v = float(value_lit.toPython())
                value = None if (math.isnan(v) or math.isinf(v)) else v
            except Exception:
                value = str(value_lit)
            value_is_array = False
        elif has_path:
            value = None
            value_is_array = True
        else:
            continue

        unit_node = g.value(prop_node, _HAS_UNIT)
        unit = str(unit_node).split("/")[-1] if unit_node else ""
        unit_uri = str(unit_node) if unit_node else ""

        wf_id = str(wf_node) if wf_node else ""
        samples = sim_to_samples.get(wf_id, [])

        records.append(
            {
                "id": str(prop_node),
                "type": pt,
                "label": label,
                "value": value,
                "value_is_array": value_is_array,
                "unit": unit,
                "unit_uri": unit_uri,
                "workflow_id": wf_id,
                "sample_ids": samples,
            }
        )

    records.sort(key=lambda r: (r["type"], r["label"], r["id"]))
    return records


# ── Memoised access ─────────────────────────────────────────────────────────
# The record list is large (100k+). Load it once and derive the summary from it,
# rather than re-reading the 47 MB cache file on every request.

_records: list | None = None
_summary: list | None = None


def invalidate() -> None:
    """Drop the memoised records/summary. Called after the KG is reloaded."""
    global _records, _summary
    _records = None
    _summary = None


def _load() -> list:
    global _records
    if _records is None:
        _records = read_cache("properties.json") or _build_properties_live()
    return _records


def _build_summary(records: list) -> list:
    """One row per property type: counts, unit, and min/max/mean of scalars."""
    acc: dict[str, dict] = {}
    for r in records:
        t = r.get("type") or "Unknown"
        a = acc.get(t)
        if a is None:
            a = acc[t] = {
                "type": t, "count": 0, "scalar_count": 0, "array_count": 0,
                "unit": r.get("unit") or "", "unit_uri": r.get("unit_uri") or "",
                "min": None, "max": None, "_sum": 0.0, "_n": 0,
            }
        a["count"] += 1
        if r.get("value_is_array"):
            a["array_count"] += 1
            continue
        a["scalar_count"] += 1
        v = r.get("value")
        if isinstance(v, (int, float)) and not isinstance(v, bool):
            a["min"] = v if a["min"] is None else min(a["min"], v)
            a["max"] = v if a["max"] is None else max(a["max"], v)
            a["_sum"] += v
            a["_n"] += 1
        if not a["unit"] and r.get("unit"):
            a["unit"] = r["unit"]
            a["unit_uri"] = r.get("unit_uri") or ""

    out = []
    for a in acc.values():
        n = a.pop("_n")
        total = a.pop("_sum")
        a["mean"] = (total / n) if n else None
        out.append(a)
    return sorted(out, key=lambda a: a["type"])


def _get_summary() -> list:
    global _summary
    if _summary is None:
        _summary = _build_summary(_load())
    return _summary


@router.get("/summary")
def summary():
    """Per-type aggregates — what the Properties tab renders."""
    rows = _get_summary()
    return {
        "types": rows,
        "total": sum(r["count"] for r in rows),
        "scalar_total": sum(r["scalar_count"] for r in rows),
    }


@router.get("")
def list_properties(
    type: str | None = None,
    search: str | None = None,
    limit: int = 100,
    offset: int = 0,
):
    """Paginated property records, optionally filtered by type and label.

    Filtering happens here rather than in the browser: with 100k+ records the
    client can only filter what it has already downloaded, which is exactly the
    problem pagination is meant to solve.
    """
    limit = max(1, min(limit, 1000))
    offset = max(0, offset)

    records = _load()
    if type:
        records = [r for r in records if r.get("type") == type]
    if search:
        q = search.lower()
        records = [
            r for r in records
            if q in str(r.get("label", "")).lower() or q in str(r.get("id", "")).lower()
        ]

    return {
        "items": records[offset:offset + limit],
        "total": len(records),
        "limit": limit,
        "offset": offset,
    }
